descriptor-schema-version: "2.2"
info:
  name: foglamp
  version: 1.5.1
app:
  type: docker
  cpuarch: x86_64
  env:
    FOGLAMP_ROOT: /usr/local/foglamp
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/foglamp/bin
  resources:
    profile: c1.large
    network:
      -
        interface-name: eth0
        ports:
          tcp: [80, 8081, 1995]
  startup:
    rootfs: rootfs.tar
    target:
      ["bash","/usr/local/foglamp/foglamp.sh"]
  